apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: VictoriaMetrics
    access: proxy
    url: http://victoriametrics:8428
    editable: false
    isDefault: true

  - name: Tempo
    type: tempo
    uid: Tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    basicAuth: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'VictoriaMetrics'

  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    uid: ClickHouse
    access: proxy
    basicAuth: false
    editable: false
    url: http://clickhouse:8123
    user: default
    secureJsonData:
      password: intuito
    jsonData:
      defaultDatabase: default
      addCorsHeader: true
      useYandexCloudAuthorization: false
      xHeaderUser: default
      usePOST: true
      ssl: false
