services:
  # .NET Application

  # OpenTelemetry Collector
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./Monitoreo/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      clickhouse:
        condition: service_healthy
      victoriametrics:
        condition: service_started
      tempo:
        condition: service_started
    restart: always

  # Grafana
  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=grafana-polystat-panel,vertamedia-clickhouse-datasource
    volumes:
      - ./Monitoreo/grafana/provisioning:/etc/grafana/provisioning
      - ./Monitoreo/grafana/dashboards:/etc/grafana/dashboards
      - ./Monitoreo/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - victoriametrics
      - tempo
      - clickhouse

  # VictoriaMetrics (Prometheus alternative for metrics)
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.93.5
    ports:
      - "8428:8428"
    command:
      - "-retentionPeriod=30d"

  # Tempo (Tracing)
  tempo:
    image: grafana/tempo:2.3.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./Monitoreo/tempo-config.yaml:/etc/tempo.yaml
      - ./Monitoreo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo

  # ClickHouse (Logs)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./Monitoreo/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=intuito
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8123/ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
